sudo: required
services:
  - docker

before_install:
  - docker build -t akshat105/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akshat105/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-449467373802"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY